### PR TITLE
Release 1.2

### PR DESCRIPTION
**Pull request by chipshort**
As discussed, I switched to Keep a Changelog because the changelog generator is buggy with the feature branches and is pretty much unmaintained.

Will release when this is approved

### CODE REVIEW

**Review by webmaster128 — APPROVED** [review]
Thanks!

**Comment by maurolacy** [comment]
Re

> As discussed, I switched to Keep a Changelog because the changelog generator is buggy with the feature branches 

Just realised that you can use `github_changelog_generator` `--release-branch <RELEASE-BRANCH>` option to work with feature branches.

`update_changelog.sh` accepts that parameter and passes it unmodified to `github_changelog_generator`. So, it works.

> and is pretty much unmaintained.

That may be. ;-)

**Comment by chipshort** [comment]
Yes, I know about the `--release-branch` flag, but it did not work correctly for me at the time. I don't remember my exact problem with it, but there are some open issues on the generator repo regarding that.

**Comment by maurolacy** [comment]
> Yes, I know about the `--release-branch` flag, but it did not work correctly for me at the time. I don't remember my exact problem with it, but there are some open issues on the generator repo regarding that.

Yes. The problem is that the current version of the script doesn't allow pass through of options to the GitHub changelog script.
That worked in the past, but got broken with the introduction of getopt option parsing.

I plan to fix it, either by fixing options pass through, or declaring required / desired options explicitly on the script.

**Pull request merged**
